export const ACTION_TYPES = {
  SET_HABIT: "SET_HABIT",
  SET_ARCHIVE: "SET_ARCHIVE",
  SET_DELETE: "SET_DELETE",

  SHOW_ADD_HABIT_MODAL: "SHOW_ADD_HABIT_MODAL",
  SHOW_EDIT_HABIT_MODAL: "SHOW_EDIT_HABIT_MODAL",
  HANDLE_MODAL_CLOSE: "HANDLE_MODAL_CLOSE"
};
